name: serv-o-laravel-dev

services:
    serv-o-laravel:
        build:
            context: '.'
            dockerfile: Dockerfile
            # args:
            #     WWWGROUP: '${WWWGROUP}'
        container_name: serv-o-laravel
        ports:
            - 80:8000
            - 5173:5173
        volumes:
            - '..:/app'
            - 'vendor_cache:/app/vendor'
            - 'node_modules_cache:/app/node_modules'
        command: sh -c "npm install && composer install && composer run dev"
        networks:
            - serv-o-network

    db:
        image: mysql:8.0
        container_name: serv-o-laravel-db
        environment:
            MYSQL_ROOT_PASSWORD: Password1234*
            MYSQL_USER: serv-user
            MYSQL_PASSWORD: 1234
            MYSQL_DATABASE: serv-o-db
        ports:
        - "3306:3306"
        networks:
            - serv-o-network

networks:
    serv-o-network:
        driver: bridge

volumes:
    vendor_cache:
    node_modules_cache:
